### ISSUE TITLE
[Bug] require('NativeModules').SpeechSynthesizer is undefined

### ISSUE THREAD

**Issue by JonathanWi** [naoufal/react-native-speech#1]
Hi,

Your plugin looks very promising, and I'd love to use it in my current project, but it seems that - since React core update (see https://github.com/facebook/react-native/issues/1821 ), SpeechSynthesizer is not part of the core anymore.

When trying to install your plugin, I'm prompted with an error screen due tu SpeechSynthesizer not being part of NativeModules. 

Any Ideas on how to fix this?

Cheers

**Comment by naoufal** [comment]
Looks like it's just a matter of updating the [require](https://github.com/naoufal/react-native-speech/blob/master/SpeechSynthesizer.ios.js#L7).

Could you submit a PR if you have time?  Otherwise, I'll tackle this over the weekend.

**Comment by JonathanWi** [comment]
Hey thanks for the quick answer! I'm not sure how to update the require to be honest, would really appreciate if you have the time to do it!

Have a great week-end

**Comment by aportner** [comment]
I got this to work by following the instructions at: http://facebook.github.io/react-native/docs/linking-libraries-ios.html#content

there's an xcode project for the speech module that you drag in and add to your linker

**Comment by naoufal** [comment]
@aportner is there anything you think I should add to the readme to make it more helpful?

**Comment by aportner** [comment]
nope, I think that's good. this was the first react native module I used, so I'm glad you included those instructions.

**Comment by aportner** [comment]
maybe move the "Linking the Library" part of the readme under Installation?

**Comment by naoufal** [comment]
Thanks for the feedback @aportner.

**Comment by joshbuchea** [comment]
I don't believe this issue was ever resolved. I am facing this same issue currently with React Native 0.14.2. The issue appears to be related to [facebook/react-native#1821](https://github.com/facebook/react-native/issues/1821) like @JonathanWi stated initially.

I tried updating the require without success. It appears that NativeModules.SpeechSynthesizer does not evaluate to an object.

**Comment by nicholasalanbrown** [comment]
I'm having hte same problem @joshbuchea on 0.14.2.

**Comment by nicholasalanbrown** [comment]
Never mind, just got it working. This is the require update I had to make in ```SpeechSynethesizer.ios.js``` to get it to work:

```
var NativeSpeechSynthesizer = require('react-native').NativeModules.SpeechSynthesizer;
var invariant = require('react-native').invariant;
```

Note, this is not the same as the PR submitted by Yonas which reads like this:
```
var NativeSpeechSynthesizer = require('react-native').NativeModules;
// var invariant = require('invariant');
var invariant = require('react-native').invariant;
```

**Comment by aladante** [comment]
Hey, still new to coding but got kind of the same problem as above. but updating the require in SpeechSynethesizer.ios.js didn't work for me. got the error 

undefined is not an object('evaluating NativeSpeechSynthesizer .stopSpeakingAtBoundary')

any ideas ?

cheers

**Comment by ghost** [comment]
Did you rebuild your ios project in xcode?

**Comment by ksrawat** [comment]
link the xcodeproj and re-run the app.. should work fine.. It works fine for me.
