### ISSUE TITLE
evaluating NativeSpeechSynthesizer .stopSpeakingAtBoundary

### ISSUE THREAD

**Issue by aladante** [naoufal/react-native-speech#12]
Hey, still new to coding but got this error undefined is not an object('evaluating NativeSpeechSynthesizer .stopSpeakingAtBoundary') . tried updating the require as an other post with kinda the same error sugested.

any ideas ?

cheers

**Comment by AtixD** [comment]
+1

**Comment by ghost** [comment]
I ran into this issue after following the linking steps in the react native docs.  I forgot to rebuild my project after linking in the library.  After a rebuild it all worked for me.  I hope this helps.

**Comment by aladante** [comment]
Thanks  for the response Allen Manning i will try let you know if it works!

**Comment by aladante** [comment]
Got the problem fixed, the liberies where wrong connected.

**Comment by haseeb-islam** [comment]
hi
your link in Linking the Library section is not working please check.
https://facebook.github.io/react-native/docs/linking-libraries.html#content
