### ISSUE TITLE
Sounds stupid

### ISSUE THREAD

**Issue by bradynapier** [naoufal/react-native-speech#2]
Super slow - cant seem to change the utterance rate?  Takes like 6 seconds to say a sentence with weird pauses.

**Comment by bradynapier** [comment]
I don't really know how to use github but I made some revisions to add the following API:

Speech.speak({
  text: 'The Garage Door is Closing',
  voice: 'en-US',
  rate: 0.50,
});

This allows you to set the spech rate from within the speak command.

     // Set args to variables
     NSString *text = args[@"text"];
     NSString *voice = args[@"voice"];
     NSNumber *speed = args[@"rate"];


     if (speed) {
        NSLog(@"Speed Defined");
     } else {
        speed = [NSNumber numberWithDouble: 0.25];
     }

     // SHOULD BE SET BY ARGUMENT
      utterance.rate = [speed doubleValue];

**Comment by tannewt** [comment]
I implemented this in #4.

**Comment by bradennapier** [comment]
Cool :)

**Comment by naoufal** [comment]
@bradennapier, This issue has been fixed and published to npm. https://www.npmjs.com/package/react-native-speech
