### ISSUE TITLE
Wont Archive - Need to Add Search Header [WITH FIX]

### ISSUE THREAD

**Issue by bradynapier** [naoufal/react-native-speech#3]
You need to search the node_modules during archive or it will fail.  Add this to the pbxproj file in the xcodeproj

     "$(SRCROOT)/../../node_modules/react-native/React/**",

If you don't do this step you will get the error that RCTBridge not Found.

**Comment by naoufal** [comment]
@bradynapier Could you submit a PR?

**Comment by Sherlock92** [comment]
Also caught this issue when archiving

**Comment by Sherlock92** [comment]
@bradynapier i'm a bit lost with how to fix this, if you could PR you'd have a new best friend ;)

**Comment by alekseiko** [comment]
Hi, there

I have the same problem. This fix helped me to resolve such problem.
