### ISSUE TITLE
Unable to resolve module NativeModules

### ISSUE THREAD

**Issue by YonasBerhe** [naoufal/react-native-speech#8]
Hello, 

I'm simply trying to require this library as a module within my application, and it just doesn't work. I have successfully added your other library react-native-activity-view to my application with no errors at all, I also followed the facebook docs like you suggested. 

```
Unable to resolve module NativeModules from /path/tomy/home/dir/node_modules/react-native-speech/SpeechSynthesizer.ios.js: Invalid 
```
```
Unable to resolve module NativeModules
```

Commenting out your require on NativeModules prompted that **invariant ** could not be found as a module.
```
Unable to resolve module invariant
```
I'm actively researching these issues, any help would be  greatly appreciated.

**Comment by YonasBerhe** [comment]
?

**Comment by joshbuchea** [comment]
Same issue here.

`npm install --save invariant` in your project directory should resolve the invariant message.

**Comment by YonasBerhe** [comment]
Ya still getting the same error.

**Comment by YonasBerhe** [comment]
#9

**Comment by nicholasalanbrown** [comment]
+1 - this library won't work on React Native 0.14+ without this fix.

**Comment by joshbuchea** [comment]
+1

**Comment by xdamman** [comment]
+1
